### ISSUE TITLE
Trocar a cifra

### ISSUE THREAD

**Issue by jtemporal** [jtemporal/caipyra#2]
A cifra atual é a mesma que a utilizada pelo `import this`. Seria legal colocar uma cifra diferente.

**Comment by odanoburu** [comment]
talvez seja óbvio e eu não esteja percebendo, mas pq cifrar o texto?

**Comment by jtemporal** [comment]
@odanoburu só pela diversão msm :) talvez algm esteja brincando com isso é queira

**Comment by odanoburu** [comment]
ah tá ! aqui tem algumas opções simples, em python puro: https://github.com/lukaszbanasiak/python-ciphers

**Comment by jcemelanda** [comment]
I'm on this one too ;)

**Comment by jcemelanda** [comment]
Implementei no PR #27

**Comment by jtemporal** [comment]
fixed by #27
