### ISSUE TITLE
Deploy automatico para o PyPI

### ISSUE THREAD

**Issue by jtemporal** [jtemporal/caipyra#21]
algo tipo o que foi feito para [deploy da serenata-toolbox](https://github.com/datasciencebr/serenata-toolbox/blob/3bb7358c889cbcb0e7ceca6e5bc64b200cce9231/.travis.yml#L15-L23)

**Comment by mstuttgart** [comment]
@jtemporal já fiz isso em um projeto meu. Posso assumir essa issue?

**Comment by jtemporal** [comment]
@mstuttgart manda ai =) eu fiz o código linkado ali em cima pra serenata-toolox. vou adorar ver uma versão diferente 😉
