### ISSUE TITLE
Melhorar o print

### ISSUE THREAD

**Issue by jtemporal** [jtemporal/caipyra#5]
Como o texto é muito grande, seria melhor se o poema fosse printado por partes na tela.

**Comment by jtemporal** [comment]
@josecostamartins da uma olhada no que o @muriloviana fez... talvez de pra gnt trabalhar algo a partir de la =)

**Comment by jcemelanda** [comment]
I'm on it @jtemporal

**Comment by jcemelanda** [comment]
Implementado no PR #27

**Comment by jtemporal** [comment]
fixed on #27
