### ISSUE TITLE
from caipyra import java nao funciona

### ISSUE THREAD

**Issue by jtemporal** [jtemporal/caipyra#6]
`from caipyra import java` deveria printar `É mentiiiira!!!` no console e só faz o print do poema

**Comment by muriloviana** [comment]
Acho que essa issue foi resolvida no PR #7 pelo @mateuspadua 
Se não tiver mais pendências, poderia fechá-la.

**Comment by jtemporal** [comment]
vdd @muriloviana esqueci de fechar =P
